### ISSUE TITLE
How can I style a docking panel?

### ISSUE THREAD

**Issue by misaunde** [cogman/javadocking#4]
How can I style a docking panel?

I'm trying to figure out how to change the docked tabs border, tab color, etc.

I've been unable to touch it with the UIManager targeting TabbedPane. I've tried things like:
```
UIManager.put("TabbedPane.selectedLabelShift", 0);
UIManager.put("TabbedPane.borderHightlightColor", new ColorUIResource( Color.RED ));
```

**Comment by cogman** [comment]
I'll be honest, this fork was for 2 things, getting this library working on java 11 and pushing it to maven central.

I'd strongly suggest, if this is a new project, that you look into other solutions.  The original author is long gone and this library is only really being semi-maintained (IE, updated to work with newer java) because my company is using it.

I can't tell you exactly how to style things, I don't know for sure unfortunately.
